# Generated by Django 4.0.3 on 2022-03-03 12:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
