# Generated by Django 4.0.3 on 2022-03-03 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0003_alter_author_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='avator100',
            new_name='avator',
        ),
        migrations.RemoveField(
            model_name='author',
            name='avator50',
        ),
    ]
