# Generated by Django 4.0.3 on 2022-03-04 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0005_author_avatar_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avator',
            field=models.FileField(blank=True, upload_to='profile_photos'),
        ),
    ]
