# Generated by Django 4.0.3 on 2022-03-04 06:54

import authors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0008_alter_author_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avatar_thumbnail',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='author',
            name='avator',
            field=models.ImageField(blank=True, upload_to=authors.models.mainImage_path),
        ),
    ]
