# Generated by Django 4.0.3 on 2022-03-04 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0011_alter_author_avator_alter_photo_file'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='File',
        ),
    ]
