# Generated by Django 4.0.3 on 2022-03-04 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0012_rename_photo_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='content_type',
            field=models.CharField(blank=True, editable=False, max_length=128, null=True),
        ),
    ]
