# Generated by Django 4.0.3 on 2022-03-04 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0014_alter_file_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
