# Generated by Django 4.0.3 on 2022-03-04 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_file_file100_file_file360_file_file800_and_more'),
        ('authors', '0015_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='avator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='files.file'),
        ),
    ]
