# Generated by Django 4.0.3 on 2022-03-04 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0017_remove_author_avatar_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='avator',
        ),
    ]
