# Generated by Django 4.0.3 on 2022-03-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0019_author_avator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='discord',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='discord'),
        ),
        migrations.AlterField(
            model_name='author',
            name='facebook',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='facebook'),
        ),
        migrations.AlterField(
            model_name='author',
            name='instargram',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='instargram'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=50, null=True, unique=True, verbose_name='작가명'),
        ),
        migrations.AlterField(
            model_name='author',
            name='twitter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='twitter'),
        ),
    ]
