# Generated by Django 4.0.3 on 2022-03-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authors', '0020_alter_author_discord_alter_author_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='작가 컨텐츠'),
        ),
    ]
