# Generated by Django 4.0.3 on 2022-03-04 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authors', '0015_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('caption', models.CharField(max_length=80, verbose_name='사진이름')),
                ('file', models.FileField(upload_to='profile_photos')),
                ('content_type', models.CharField(blank=True, editable=False, max_length=128, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='authors.author')),
            ],
            options={
                'verbose_name': '파일',
                'verbose_name_plural': '파일모음',
            },
        ),
    ]
