# Generated by Django 4.0.3 on 2022-03-04 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0005_file_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='author',
        ),
    ]
