# Generated by Django 4.0.3 on 2022-03-04 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0006_remove_file_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='author',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='작가이름'),
        ),
        migrations.AlterField(
            model_name='file',
            name='caption',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='사진이름'),
        ),
    ]
