# Generated by Django 4.0.3 on 2022-03-05 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0007_file_author_alter_file_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='file100',
        ),
    ]
