# Generated by Django 4.0.3 on 2022-03-05 07:16

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_projecttype_alter_product_producttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
            ],
            options={
                'verbose_name': 'Tags',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image100',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='', verbose_name='image100'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image200',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='', verbose_name='image200'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image400',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='', verbose_name='image400'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image800',
            field=models.FileField(blank=True, max_length=300, null=True, upload_to='', verbose_name='image800'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main',
            field=models.BooleanField(default=False, verbose_name='메인작품'),
        ),
        migrations.RemoveField(
            model_name='product',
            name='tags',
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags', to='products.tag'),
        ),
    ]
