# Generated by Django 4.0.3 on 2022-03-05 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_alter_file_file'),
        ('products', '0007_alter_product_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image100',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image200',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image400',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image800',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='files.file'),
        ),
    ]
